# Generated by Django 5.0.3 on 2024-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_note_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='descr',
            field=models.TextField(default=''),
        ),
    ]
