# Generated by Django 5.0.3 on 2024-03-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_note_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='descr',
        ),
    ]
